### PR TITLE
Add Launchpad support to DAMP_RT.

### PR DESCRIPTION
**Pull request by juicermv**
Added Launchpad support via a preprocessor definition.
You can choose to get either only the normals or motion vectors or both.

I've added an explanation in the UI as well.

### CODE REVIEW

**Comment by Zenteon** [comment]
Already have launchpad MV's working in a beta release, as well as my own significantly faster smooth normal solution.

**Comment by juicermv** [comment]
Oh great lol, didn't see anything about it here so I assumed this wasn't implemented yet :) would love to see that beta branch

**Comment by juicermv** [comment]
Did you get the temporal smoothing working with it btw?

**Comment by Zenteon** [comment]
It's currently testing on discord, next release should be relatively soon. If you want to take a look at it in the meantime I can give you beta tester access

**Comment by Zenteon** [comment]
> Did you get the temporal smoothing working with it btw?

Not sure why it wouldn't work, launchpad mvs are a drop in replacement for most others, temporal smoothing works fine with them.

**Comment by juicermv** [comment]
> It's currently testing on discord, next release should be relatively soon. If you want to take a look at it in the meantime I can give you beta tester access

I'd love to



> > Did you get the temporal smoothing working with it btw?
> 
> Not sure why it wouldn't work, launchpad mvs are a drop in replacement for most others, temporal smoothing works fine with them.

I get a lot more noise with them for some reason. I think it might be because they're not updated at full rate but idk.

**Comment by Zenteon** [comment]
Server link is in the readme, let me know it's you when you join so I can give you access

**Comment by juicermv** [comment]
Sure

**Pull request closed without merging**
